name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ toLower(github.repository) }}/backend
          docker build . --file Dockerfile \
            --tag $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:${GITHUB_SHA}

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ toLower(github.repository) }}/backend
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${GITHUB_SHA}
